### ISSUE TITLE
Undefined array key "plugins"

### ISSUE THREAD

**Issue by artmem** [ryssbowh/craft-redactor-fa-api#1]
I'm using the plugin successfully in multiple places, but I have one global set that throws the following error when trying to load the page:

Undefined array key "plugins"
1. in /app/vendor/ryssbowh/craft-redactor-fa-api/src/services/FaService.php at line 62

```
    /**
     * Modify redactor config
     *
     * @param  array  $config
     * @return array
     */
    public function modifyRedactorConfig(array $config): array
    {
        if (!in_array('fontawesome', $config['plugins'])) {
            return $config;
        }
        $settings = RedactorFa::$plugin->settings;
        $config['redactorFaApi'] = [
            'mode' => $settings->mode,
            'version' => $settings->faVersion,
            'license' => $settings->faLicense,
            'preventReplaceI' => $settings->preventReplaceI
        ];

```

I only have one redactor config setup that uses the plugin, and I'm using it I'm multiple entry and global fields with no problems. I only get the error on this particular globals page.

**Comment by ryssbowh** [comment]
Thanks for reporting this, there was an issue when no plugins were defined in redactor.
I fixed it in 1.0.1
