### ISSUE TITLE
The text after selecting icon always inside the em or i tags

### ISSUE THREAD

**Issue by aodihis** [ryssbowh/craft-redactor-fa-api#2]
When we selecting the icons and after that we type the text, the text always goes to inside the <i> or <em> tags, and cannot put text outside that tags.

So, here is the example : 
`<p><em class="fa-solid fa-truck-ramp-box"> sd</em></p>`

The text sd is wrapped inside the <em> tags, that i should not. This is what we expected

`<p><em class="fa-solid fa-truck-ramp-box"></em>sd</p>`

Btw Also looks like the plugin didn't support fa version 5, the icons are not showing if we use version 5 font-awesome.

**Comment by ryssbowh** [comment]
I don't think there's anything that can be done for the text problem, this is a problem with redactor itself I believe.
I noticed if you add your icons after typing the text you don't have that problem

**Comment by ryssbowh** [comment]
Ha I didn't see your PR included a fix for that, I added it now
