### ISSUE TITLE
FR: Style options before insert

### ISSUE THREAD

**Issue by wmdhosting** [ryssbowh/craft-redactor-fa-api#4]
Hello :)

Works all great, 
will be much better if there are at least some style options before insert  in Redactor

**Comment by ryssbowh** [comment]
Hi,
What style options would you see ? you mean like some extra css classes ?

**Comment by wmdhosting** [comment]
yes. just basic thing that are here.   on font awesome page.. 
so user can choose some option before inserting. in content  ..  
that options just add classes
![Snag_a796c94](https://user-images.githubusercontent.com/76176291/163926670-7ec7ffc8-e3e9-4882-9571-65fcf9d0c606.png)

As now need to go in code to change...
It will be quite more user firendly..

**Comment by ryssbowh** [comment]
I see, will have a look soon

**Comment by wmdhosting** [comment]
OK thx :)

**Comment by ryssbowh** [comment]
Hi,
I've added this to versions 1.0.5 (Craft 3) and 2.0.0 (Craft 4)

**Comment by wmdhosting** [comment]
thank you :)
